name: electricity-feature-and-prediction-pipelines

on:

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule the workflow to run at 23:50 everyday
  schedule:
   - cron: '50 23 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute python workflows from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: ./scripts/run_feature_and_prediction_pipelines.sh

      

